version: '3.7'

services:
  db:
    environment:
      - POSTGRES_PASSWORD=production-pg-password
    # hostname: db.docker-rails.my-site.com
    image: postgres:11.6-alpine
    ports:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - /my-volumes/docker-rails/postgresql:/var/lib/postgresql/data

  redis:
    # hostname: redis.docker-rails.my-site.com
    image: redis:alpine
    restart: always
    volumes:
      - /my-volumes/docker-rails/redis:/data

  app: &app_base
    image: rebelsmanager_app_production
    build:
      context: .
      args:
        - FOLDERS_TO_REMOVE=spec node_modules app/assets vendor/assets lib/assets tmp/cache
        - BUNDLE_WITHOUT=development:test
        - EXECJS_RUNTIME=Disabled
        - RAILS_ENV=production
    environment:
      - ALLOWED_ORIGINS=rebels-docker.extinctionrebellion.be
      - APP_TYPE=production
      - APP_URL=https://rebels-docker.extinctionrebellion.be
      - LOCKBOX_MASTER_KEY=[generate-one-with-lockbox-generate_key]
      - XR_BRANCH_DEFAULT_LANGUAGE=en
      - XR_BRANCH_TIMEZONE=Europe/Brussels
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=[production-pg-password]
      - POSTGRES_USER=postgres
      - CERT_NAME=rebels-docker.extinctionrebellion.be
      - LETSENCRYPT_EMAIL=it@extinctionrebellion.be
      - LETSENCRYPT_HOST=rebels-docker.extinctionrebellion.be
      - RAILS_ENV=production
      - RAILS_MAX_THREADS=5
      - REDIS_CABLE_URL=redis://redis:6379/1
      - REDIS_SIDEKIQ_URL=redis://redis:6379/0
      - REDIS_CACHE_URL=redis://redis:6379/2
      - SECRET_KEY_BASE=[my-secret-access-key]
      - MAILTRAIN_API_ENDPOINT=https://lists.extinctionrebellion.be/api
      - MAILTRAIN_API_TOKEN=[paste-token-here]
      - MAILTRAIN_REBELS_LIST_ID=[paste-main-list-id-here]
    hostname: rebels-docker.extinctionrebellion.be
    links:
      - db
      - redis
    ports:
      - 3000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 3000 || exit 1"]
      interval: 5m
      start_period: 1m

  worker:
    <<: *app_base
    command: bundle exec sidekiq
    # hostname: worker.docker-rails.my-site.com
    healthcheck:
      test: "ps ax | grep -v grep | grep sidekiq"
      interval: 1m
      start_period: 1m
